# Generated by Django 5.0.4 on 2024-05-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadsheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.CharField(max_length=12, verbose_name='作成日')),
                ('manager', models.CharField(max_length=8, verbose_name='担当者')),
                ('category', models.CharField(max_length=30, verbose_name='カテゴリー')),
                ('question_id', models.TextField(verbose_name='問題ID')),
                ('question_number', models.CharField(max_length=12, verbose_name='問題番号')),
                ('chapter', models.CharField(max_length=12, verbose_name='章')),
                ('heading', models.CharField(max_length=30, verbose_name='見出し')),
                ('question', models.TextField(blank=True, null=True, verbose_name='問題の本文')),
                ('level', models.CharField(max_length=1, verbose_name='レベル')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='ヒント')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='回答例')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='解説')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('question_c_plus_plus', models.TextField(blank=True, null=True, verbose_name='問題の本文(C++)')),
                ('answer_c_plus_plus', models.TextField(blank=True, null=True, verbose_name='解答例(C++)')),
            ],
        ),
    ]
